NUM_CLIENTS=30
NUM_BACKUPS=0
NUM_COUCHBASE_SERVERS_DATA_CLUSTER1=130
NUM_COUCHBASE_SERVERS_DATA_CLUSTER2=0
NUM_COUCHBASE_SERVERS_DATA_CLUSTER1_NEW=0
NUM_COUCHBASE_SERVERS_DATA_CLUSTER2_NEW=0
NUM_COUCHBASE_SERVERS_INDEX=0
NUM_COUCHBASE_SERVERS_QUERY=0

# minimum of 1, maximum of 4
CLUSTER1_NUM_SERVER_GROUPS=1

CLUSTER1_AVAILABILITY_ZONE="us-east-1a"
CLUSTER2_AVAILABILITY_ZONE="us-east-1c"

CLIENT_INSTANCE_TYPE="c4.8xlarge"
COUCHBASE_INSTANCE_TYPE="r3.4xlarge"
#CLIENT_INSTANCE_TYPE="t2.micro"
#COUCHBASE_INSTANCE_TYPE="t2.micro"
BACKUP_INSTANCE_TYPE="r3.4xlarge"

CLIENT_IMAGE= "ami-5fa0dc49"
COUCHBASE_IMAGE="ami-7f5c2569"
BACKUP_IMAGE="ami-f7f2079a"
BACKUP_SPACE="100"
S3_BUCKET_NAME="scalability-mcafee"
