- hosts: tag_Type_couchbaseserver_data_cluster1 
  vars:
    sudo: yes
    rpm_path: "/tmp/couchbase.rpm"
  remote_user: centos 
  become: yes
  become_method: sudo 
  serial: 20
  tasks:
  - copy:
      src: "{{rpm_path}}"
      dest: "{{rpm_path}" 
      mode: 0644
  - name: install couchbase
    yum: name="{{rpm_path}}"
  - name: permissions 
    shell: chown couchbase /data && chgrp couchbase /data 
